url: https://aptanadev.github.io
baseurl: /tasikstarcenter/

# Site settings
title: Tasik Star Center Electronics
email: admin@tasikstarcenter.id
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Rose Azizah 
  pic: 1
  position: Banyak barang keluaran baru, harga juga bersaing, bisa nego, pelayanan baik, ada free ice cream sepuasnya, ada kopi, dan macam minuman lainnya free untuk konsumen. 
- name: Odin Nuradin 
  pic: 2
  position: Udah beberapa kali belanja di toko tasik star center pelayanannya ramah sekali banyak hadiahnya juga jadi kita setiap pembelian ada poin juga yang bisa nanti dituker sama hadiah. 
- name: Destma Shinta Shaumi
  pic: 3
  position: Toko ternyaman lengkap dan pelayanan cepat dan ramah tempatnya bersih nyaman pokonya belanja disini jadi kalap pengen borong semua, terimakasih sukses terus Tasik Star. 
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
